name: Hello World II

on:
    push:
        branches:
            - main

jobs:
    hello:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4 # Optional
            - name: Hello World
              run: echo "Hello World!"
              shell: bash